Traceback (most recent call last):
  File "C:\Users\MyBook Z Series\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\MyBook Z Series\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MyBook Z Series\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\MyBook Z Series\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "C:\Users\MyBook Z Series\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\MyBook Z Series\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Mengkoneksi database dengan python

# for mysql
timeout = 10
connection = pymysql.connect(
    charset="utf8mb4",
    connect_timeout=timeout,
    cursorclass=pymysql.cursors.DictCursor,
    db="defaultdb",
    host="mysql-726cd75-mysqlpendata-11.h.aivencloud.com",
    password="AVNS_LHA80D-LNsKI6wncjfc",
    read_timeout=timeout,
    port=20734,
    user="avnadmin",
    write_timeout=timeout,
)
mysql_engine = create_engine("mysql+pymysql://avnadmin:AVNS_LHA80D-LNsKI6wncjfc@mysql-726cd75-mysqlpendata-11.h.aivencloud.com:20734/defaultdb")



# for postgre
def main():
    conn = psycopg2.connect('postgres://avnadmin:AVNS__Y6I8K0T7rSnwnRgE1U@pg-3266d3cf-postgresqlpendata-11.h.aivencloud.com:20817/defaultdb?sslmode=require')

    query_sql = 'SELECT VERSION()'

    cur = conn.cursor()
    cur.execute(query_sql)

    version = cur.fetchone()[0]
    print(version)

if __name__ == "__main__":
    main()
postgres_engine = create_engine("postgresql+psycopg2://avnadmin:AVNS__Y6I8K0T7rSnwnRgE1U@pg-3266d3cf-postgresqlpendata-11.h.aivencloud.com:20817/defaultdb")



------------------


[31m---------------------------------------------------------------------------[39m
[31mRuntimeError[39m                              Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[3][39m[32m, line 5[39m
[32m      1[39m [38;5;66;03m# Mengkoneksi database dengan python[39;00m
[32m      2[39m 
[32m      3[39m [38;5;66;03m# for mysql[39;00m
[32m      4[39m timeout = [32m10[39m
[32m----> [39m[32m5[39m connection = [43mpymysql[49m[43m.[49m[43mconnect[49m[43m([49m
[32m      6[39m [43m    [49m[43mcharset[49m[43m=[49m[33;43m"[39;49m[33;43mutf8mb4[39;49m[33;43m"[39;49m[43m,[49m
[32m      7[39m [43m    [49m[43mconnect_timeout[49m[43m=[49m[43mtimeout[49m[43m,[49m
[32m      8[39m [43m    [49m[43mcursorclass[49m[43m=[49m[43mpymysql[49m[43m.[49m[43mcursors[49m[43m.[49m[43mDictCursor[49m[43m,[49m
[32m      9[39m [43m    [49m[43mdb[49m[43m=[49m[33;43m"[39;49m[33;43mdefaultdb[39;49m[33;43m"[39;49m[43m,[49m
[32m     10[39m [43m    [49m[43mhost[49m[43m=[49m[33;43m"[39;49m[33;43mmysql-726cd75-mysqlpendata-11.h.aivencloud.com[39;49m[33;43m"[39;49m[43m,[49m
[32m     11[39m [43m    [49m[43mpassword[49m[43m=[49m[33;43m"[39;49m[33;43mAVNS_LHA80D-LNsKI6wncjfc[39;49m[33;43m"[39;49m[43m,[49m
[32m     12[39m [43m    [49m[43mread_timeout[49m[43m=[49m[43mtimeout[49m[43m,[49m
[32m     13[39m [43m    [49m[43mport[49m[43m=[49m[32;43m20734[39;49m[43m,[49m
[32m     14[39m [43m    [49m[43muser[49m[43m=[49m[33;43m"[39;49m[33;43mavnadmin[39;49m[33;43m"[39;49m[43m,[49m
[32m     15[39m [43m    [49m[43mwrite_timeout[49m[43m=[49m[43mtimeout[49m[43m,[49m
[32m     16[39m [43m)[49m
[32m     17[39m mysql_engine = create_engine([33m"[39m[33mmysql+pymysql://avnadmin:AVNS_LHA80D-LNsKI6wncjfc@mysql-726cd75-mysqlpendata-11.h.aivencloud.com:20734/defaultdb[39m[33m"[39m)
[32m     21[39m [38;5;66;03m# for postgre[39;00m

[36mFile [39m[32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pymysql\connections.py:361[39m, in [36mConnection.__init__[39m[34m(self, user, password, host, database, unix_socket, port, charset, collation, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_key_password, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[39m
[32m    359[39m     [38;5;28mself[39m._sock = [38;5;28;01mNone[39;00m
[32m    360[39m [38;5;28;01melse[39;00m:
[32m--> [39m[32m361[39m     [38;5;28;43mself[39;49m[43m.[49m[43mconnect[49m[43m([49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pymysql\connections.py:669[39m, in [36mConnection.connect[39m[34m(self, sock)[39m
[32m    666[39m [38;5;28mself[39m._next_seq_id = [32m0[39m
[32m    668[39m [38;5;28mself[39m._get_server_information()
[32m--> [39m[32m669[39m [38;5;28;43mself[39;49m[43m.[49m[43m_request_authentication[49m[43m([49m[43m)[49m
[32m    671[39m [38;5;66;03m# Send "SET NAMES" query on init for:[39;00m
[32m    672[39m [38;5;66;03m# - Ensure charaset (and collation) is set to the server.[39;00m
[32m    673[39m [38;5;66;03m#   - collation_id in handshake packet may be ignored.[39;00m
[32m   (...)[39m[32m    682[39m [38;5;66;03m# - https://github.com/wagtail/wagtail/issues/9477[39;00m
[32m    683[39m [38;5;66;03m# - https://zenn.dev/methane/articles/2023-mysql-collation (Japanese)[39;00m
[32m    684[39m [38;5;28mself[39m.set_character_set([38;5;28mself[39m.charset, [38;5;28mself[39m.collation)

[36mFile [39m[32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pymysql\connections.py:979[39m, in [36mConnection._request_authentication[39m[34m(self)[39m
[32m    977[39m [38;5;66;03m# https://dev.mysql.com/doc/internals/en/successful-authentication.html[39;00m
[32m    978[39m [38;5;28;01mif[39;00m [38;5;28mself[39m._auth_plugin_name == [33m"[39m[33mcaching_sha2_password[39m[33m"[39m:
[32m--> [39m[32m979[39m     auth_packet = [43m_auth[49m[43m.[49m[43mcaching_sha2_password_auth[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mauth_packet[49m[43m)[49m
[32m    980[39m [38;5;28;01melif[39;00m [38;5;28mself[39m._auth_plugin_name == [33m"[39m[33msha256_password[39m[33m"[39m:
[32m    981[39m     auth_packet = _auth.sha256_password_auth([38;5;28mself[39m, auth_packet)

[36mFile [39m[32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pymysql\_auth.py:267[39m, in [36mcaching_sha2_password_auth[39m[34m(conn, pkt)[39m
[32m    264[39m     [38;5;28;01mif[39;00m DEBUG:
[32m    265[39m         [38;5;28mprint[39m(conn.server_public_key.decode([33m"[39m[33mascii[39m[33m"[39m))
[32m--> [39m[32m267[39m data = [43msha2_rsa_encrypt[49m[43m([49m[43mconn[49m[43m.[49m[43mpassword[49m[43m,[49m[43m [49m[43mconn[49m[43m.[49m[43msalt[49m[43m,[49m[43m [49m[43mconn[49m[43m.[49m[43mserver_public_key[49m[43m)[49m
[32m    268[39m pkt = _roundtrip(conn, data)

[36mFile [39m[32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pymysql\_auth.py:144[39m, in [36msha2_rsa_encrypt[39m[34m(password, salt, public_key)[39m
[32m    139[39m [38;5;250m[39m[33;03m"""Encrypt password with salt and public_key.[39;00m
[32m    140[39m 
[32m    141[39m [33;03mUsed for sha256_password and caching_sha2_password.[39;00m
[32m    142[39m [33;03m"""[39;00m
[32m    143[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m _have_cryptography:
[32m--> [39m[32m144[39m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[32m    145[39m         [33m"[39m[33m'[39m[33mcryptography[39m[33m'[39m[33m package is required for sha256_password or[39m[33m"[39m
[32m    146[39m         + [33m"[39m[33m caching_sha2_password auth methods[39m[33m"[39m
[32m    147[39m     )
[32m    148[39m message = _xor_password(password + [33mb[39m[33m"[39m[38;5;130;01m\0[39;00m[33m"[39m, salt)
[32m    149[39m rsa_key = serialization.load_pem_public_key(public_key, default_backend())

[31mRuntimeError[39m: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

